version: "2"
linters:
  default: none
  enable:
    - copyloopvar
    - durationcheck
    - errcheck
    - godot
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usetesting
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - linters:
          - unparam
        text: always receives
      - linters:
        - staticcheck
        text: 'SA1019: stateConf.WaitForState is deprecated: Please use WaitForStateContext to ensure proper plugin shutdown'
      - linters:
        - staticcheck
        text: 'SA1019: retry.Retry is deprecated: Please use RetryContext to ensure proper plugin shutdown'
      - linters:
        - staticcheck
        text: 'SA1019: schema.ImportStatePassthrough is deprecated: Please use the context aware ImportStatePassthroughContext instead '
  settings:
    errcheck:
      exclude-functions:
        - (*github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.ResourceData).Set
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
